<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Cirkulaer.ServiceDefaults\Cirkulaer.ServiceDefaults.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableSdkContainerSupport>true</EnableSdkContainerSupport>
  </PropertyGroup>

  <ItemGroup>
    <Content Update="data\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
